GET  http://localhost:5001/Pent



###
POST http://localhost:5001/Pent/post
Content-Type: application/json

{
    "name":"olushola",
    "email":"example@email",
    "username":"Gbenga",
    "phoneNumber":"38393038"
}


###
GET  http://localhost:5001/Pent/user




###
DELETE  http://localhost:5001/Pent/user/delete/63033b70cdbbfafae476f421




###
POST http://localhost:5001/Pent/post/review
Content-Type: application/json

{
    "username":"abiona",
    "landlordReview":"rude",
    "EnvironmentReview":"not clean",
    "QualityofAmentities":"bad",
    "file":"",
}
 
###
GET  http://localhost:5001/Pent/review

