GET  http://localhost:5001/Pent



###
POST http://localhost:5001/Pent/post
Content-Type: application/json

{
    "name":"olushola",
    "email":"example@email",
    "username":"Gbenga",
    "phoneNumber":"38393038"
}


###
GET  http://localhost:5001/Pent/user




###
DELETE  http://localhost:5001/Pent/user/delete/6320da0e8c3dadbce0715e66




###
POST http://localhost:5001/Pent/post/review
Content-Type: application/json

{
    "username":"olushola",
    "landlordReview":"req.body.landlordReview",
    "EnvironmentReview":"req.body.EnvironmentReview",
    "QualityofAmentities":"req.body.QualityofAmentities",
    "file":""
}
 
###
GET  http://localhost:5001/Pent/review




###
DELETE http://localhost:5001/Pent/review/delete/6320dc692c590eb77310fc58